---

- repo: local
  hooks:
    - id: isort
      name: isort
      entry: 'pipenv run isort'
      language: system
    - id: flake8
      name: flake8
      entry: 'pipenv run flake8'
      exclude: ^.*(?<!\.py)$
      language: system
    - id: mypy
      name: mypy
      entry: 'pipenv run mypy'
      exclude: ^.*(?<!\.py)$
      language: system
