# Generated by Django 2.1.4 on 2019-01-20 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_type', models.CharField(choices=[('telegram_channel', 'Telegram Channel'), ('telegram_supergroup', 'Telegram Supergroup (chat)'), ('vk_group', 'VK Group (public)')], max_length=32)),
                ('text', models.TextField(blank=True)),
                ('current_status', models.CharField(choices=[('scheduled', 'Post was scheduled'), ('sending', 'Post is sending'), ('failed', 'Sending was failed'), ('success', 'Sending was success')], default='scheduled', editable=False, max_length=32)),
                ('vk_clear_markdown', models.NullBooleanField(default=True)),
                ('telegram_picture_as_link', models.NullBooleanField(default=True)),
                ('telegram_markdown', models.NullBooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='platformpost',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_posts', to='api.Publication'),
        ),
    ]
