# Generated by Django 2.1.5 on 2019-01-28 22:19

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='picture',
            field=pyuploadcare.dj.models.ImageField(blank=True, null=True),
        ),
    ]
