# Generated by Django 2.1.7 on 2019-03-13 18:00

from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190128_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', pyuploadcare.dj.models.ImageField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='publication',
            name='picture',
        ),
        migrations.AddField(
            model_name='attachment',
            name='parent_publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Publication'),
        ),
    ]
